import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { buildDryadTechnicalCohortAsset } from '../src/services/dryadMotionCohort';
import { importDryadMotionTrial } from '../src/services/dryadMotionImporter';
import type { BalletMotionId, DryadMotionTrial } from '../src/types/motionRegistry';

const args = new Map(process.argv.slice(2).reduce<string[][]>((pairs, value, index, values) => (
  index % 2 === 0 ? [...pairs, [value, values[index + 1] ?? '']] : pairs
), []));
const datasetRoot = args.get('--dataset-root');
const outputPath = args.get('--output') ?? 'src/data/dryadMotionAssets.generated.ts';
if (!datasetRoot) throw new Error('Usage: --dataset-root <work/datasets> [--output <generated.ts>]');

const sha256 = (value: string | Buffer) => createHash('sha256').update(value).digest('hex');
const stableJson = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`;
const dryadRoot = resolve(datasetRoot, 'dryad_ballet_timing_2025');
const dryadManifest = JSON.parse(await readFile(resolve(dryadRoot, 'MANIFEST.json'), 'utf8'));
const movementIds = ['passe', 'jete', 'changement'] as const satisfies readonly Exclude<BalletMotionId, 'plie' | 'tendu'>[];

const assets = [];
const movementManifest = [];
for (const movementId of movementIds) {
  const referenceCsv = await readFile(resolve(dryadRoot, `extracted/MovRef_${movementId}.csv`), 'utf8');
  const inputDigests = [sha256(referenceCsv)];
  const trials: DryadMotionTrial[] = [];
  const skipped: string[] = [];
  for (let participantId = 1; participantId <= 10; participantId++) {
    let mocapCsv: string;
    try {
      mocapCsv = await readFile(resolve(dryadRoot, `extracted/Mocap_${movementId}_${participantId}.csv`), 'utf8');
    } catch {
      skipped.push(`p${participantId}:source_file_missing`);
      continue;
    }
    inputDigests.push(sha256(mocapCsv));
    for (let trial = 1; trial <= 10; trial++) {
      try {
        trials.push(importDryadMotionTrial({
          movementId,
          mocapCsv,
          movementReferenceCsv: referenceCsv,
          participantId,
          trial,
        }));
      } catch (error) {
        skipped.push(`p${participantId}-t${trial}:${error instanceof Error ? error.message : 'unknown'}`);
      }
    }
  }
  const generatedFromDigest = sha256(inputDigests.sort().join(':'));
  const asset = buildDryadTechnicalCohortAsset({ trials, generatedFromDigest });
  assets.push(asset);
  movementManifest.push({
    movementId,
    generatedFromDigest,
    participantCount: asset.clip.participantCount,
    importedTrialCount: asset.clip.sourceTrialCount,
    skippedTrialCount: skipped.length,
    skipped,
    generatedFrameCount: asset.clip.frames.length,
  });
}

const manifest = {
  schemaVersion: 1,
  datasetId: dryadManifest.dataset_id,
  sourceArchiveSha256: dryadManifest.archive.sha256,
  license: dryadManifest.license,
  pedagogicalStatus: 'technical_only',
  nicoleReviewStatus: 'not_reviewed',
  exportedForm: 'non-reversible cohort medians and event dispersion only',
  movements: movementManifest,
};
const source = `/* eslint-disable */\n// GENERATED by tools/buildDryadMotionRegistry.ts. Do not edit by hand.\nimport type { DryadTechnicalCohortAsset } from '../types/motionRegistry';\n\nfunction deepFreeze<T>(value: T): Readonly<T> {\n  if (value && typeof value === 'object' && !Object.isFrozen(value)) {\n    Object.freeze(value);\n    Object.values(value as Record<string, unknown>).forEach(item => deepFreeze(item));\n  }\n  return value;\n}\n\nexport const DRYAD_TECHNICAL_MOTION_ASSETS = deepFreeze(${stableJson(assets).trim()}) as readonly DryadTechnicalCohortAsset[];\n\nexport const DRYAD_MOTION_ASSET_MANIFEST = deepFreeze(${stableJson(manifest).trim()});\n`;
await writeFile(resolve(outputPath), source, 'utf8');
console.log(`Generated ${outputPath}: ${assets.map(asset => `${asset.clip.exerciseId}=${asset.clip.sourceTrialCount}`).join(', ')}.`);
