import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { importBvhCanonicalMotion } from '../src/services/bvhMotionImporter';
import { buildDryadTenduCohortAsset } from '../src/services/dryadTenduCohort';
import { importDryadTenduTrial } from '../src/services/dryadTenduImporter';
import { analyzeCanonicalSpatialStability } from '../src/services/tenduTechnicalPilot';
import type { MotionDatasetProvenance } from '../src/types/canonicalMotion';

const args = new Map(process.argv.slice(2).reduce<string[][]>((pairs, value, index, values) => (
  index % 2 === 0 ? [...pairs, [value, values[index + 1] ?? '']] : pairs
), []));
const datasetRoot = args.get('--dataset-root');
const outputPath = args.get('--output') ?? 'src/data/tenduPilotAssets.generated.ts';
if (!datasetRoot) throw new Error('Usage: --dataset-root <work/datasets> [--output <generated.ts>]');

const sha256 = (value: string | Buffer) => createHash('sha256').update(value).digest('hex');
const stableJson = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`;
const dryadRoot = resolve(datasetRoot, 'dryad_ballet_timing_2025');
const ucyRoot = resolve(datasetRoot, 'ucy_ballet_internal_pilot');
const dryadManifest = JSON.parse(await readFile(resolve(dryadRoot, 'MANIFEST.json'), 'utf8'));
const ucyManifest = JSON.parse(await readFile(resolve(ucyRoot, 'MANIFEST.json'), 'utf8'));
const movementReferenceCsv = await readFile(resolve(dryadRoot, 'extracted/MovRef_tendu.csv'), 'utf8');

const clips = [];
const inputDigests: string[] = [sha256(movementReferenceCsv)];
for (let participantId = 1; participantId <= 10; participantId++) {
  const mocapCsv = await readFile(resolve(dryadRoot, `extracted/Mocap_tendu_${participantId}.csv`), 'utf8');
  inputDigests.push(sha256(mocapCsv));
  for (let trial = 1; trial <= 10; trial++) {
    clips.push(importDryadTenduTrial({ mocapCsv, movementReferenceCsv, participantId, trial }));
  }
}
const generatedFromDigest = sha256(inputDigests.sort().join(':'));
const cohort = buildDryadTenduCohortAsset({ clips, generatedFromDigest });

const bvhPath = resolve(ucyRoot, 'raw/Ballet_Ioanna_Tacha_Believer.bvh');
const bvh = await readFile(bvhPath, 'utf8');
const expectedBvhDigest = ucyManifest.assets.find((asset: { path: string }) => asset.path.endsWith('.bvh'))?.sha256;
if (!expectedBvhDigest || sha256(bvh) !== expectedBvhDigest) throw new Error('UCY BVH digest does not match its manifest.');
const ucyProvenance: MotionDatasetProvenance = Object.freeze({
  datasetId: ucyManifest.dataset_id,
  sourceUrl: ucyManifest.source_url,
  sourceKind: 'bvh_skeleton',
  rightsStatus: 'internal_research_only',
  licenseLabel: 'UCY personal single-user research pilot · derived carrier only',
  pedagogicalStatus: 'technical_only',
  nicoleReviewStatus: 'not_reviewed',
  sourceDigest: expectedBvhDigest,
});
const ucyClip = importBvhCanonicalMotion({
  bvh,
  clipId: 'ucy-believer-internal-carrier-source',
  label: 'UCY Believer · internal carrier source',
  provenance: ucyProvenance,
  frameStride: 120,
  maxFrames: 100,
});
const ucyStability = analyzeCanonicalSpatialStability(ucyClip);

const manifest = {
  schemaVersion: 1,
  dryad: {
    datasetId: dryadManifest.dataset_id,
    sourceArchiveSha256: dryadManifest.archive.sha256,
    generatedFromDigest,
    participantCount: cohort.clip.participantCount,
    trialCount: cohort.clip.sourceTrialCount,
    generatedFrameCount: cohort.clip.frames.length,
  },
  ucy: {
    datasetId: ucyManifest.dataset_id,
    sourceBvhSha256: expectedBvhDigest,
    sourceFrameCount: ucyManifest.capture.frames,
    inspectedFrameCount: ucyClip.frames.length,
    stability: ucyStability,
    exportedForm: 'aggregate stability report only; no derived joint coordinates',
    productStatus: 'internal_research_only_do_not_ship',
  },
};

const source = `/* eslint-disable */\n// GENERATED by tools/buildTenduPilotAssets.ts. Do not edit by hand.\nimport type { DryadTenduCohortAsset } from '../types/canonicalMotion';\n\nfunction deepFreeze<T>(value: T): Readonly<T> {\n  if (value && typeof value === 'object' && !Object.isFrozen(value)) {\n    Object.freeze(value);\n    Object.values(value as Record<string, unknown>).forEach(item => deepFreeze(item));\n  }\n  return value;\n}\n\nexport const DRYAD_TENDU_COHORT_ASSET = deepFreeze(${stableJson(cohort).trim()}) as DryadTenduCohortAsset;\n\nexport const TENDU_PILOT_ASSET_MANIFEST = deepFreeze(${stableJson(manifest).trim()});\n`;
await writeFile(resolve(outputPath), source, 'utf8');
console.log(`Generated ${outputPath}: ${cohort.clip.sourceTrialCount} Dryad trials, ${cohort.clip.frames.length} cohort frames.`);
