// GENERATED by tools/buildDryadMotionRegistry.ts. Do not edit by hand.
// Runtime keeps only these non-reversible temporal priors; the 250 Hz cohort
// bodies stay out of the interactive UI bundle.
export type DryadTechnicalPhasePrior = Readonly<{
  exerciseId: 'passe' | 'jete' | 'changement';
  datasetId: string;
  generatedFromDigest: string;
  expectedPeakProgress: number;
  sourceSampleCount: number;
}>;

export const DRYAD_TECHNICAL_PHASE_PRIORS: readonly DryadTechnicalPhasePrior[] = Object.freeze([
  Object.freeze({
    exerciseId: 'passe',
    datasetId: 'dryad:10.5061/dryad.dncjsxm8v:2025-01-02:passe:cohort-aggregate',
    generatedFromDigest: 'ccfb917f4c00912c3f6c2a788c20f61780e924e009afbe585482fe9f717319e1',
    expectedPeakProgress: 0.5551345654109652,
    sourceSampleCount: 100,
  }),
  Object.freeze({
    exerciseId: 'jete',
    datasetId: 'dryad:10.5061/dryad.dncjsxm8v:2025-01-02:jete:cohort-aggregate',
    generatedFromDigest: 'ae301812fcf0b8e99e80184384ac9e363439b4ac74357ee3a3b01dae91d74afd',
    expectedPeakProgress: 0.5085138575339834,
    sourceSampleCount: 100,
  }),
  Object.freeze({
    exerciseId: 'changement',
    datasetId: 'dryad:10.5061/dryad.dncjsxm8v:2025-01-02:changement:cohort-aggregate',
    generatedFromDigest: '726db5b8e283199bf98744df4b6b663e082f027f5ac351eaba1b263662c468b2',
    expectedPeakProgress: 0.500872799993221,
    sourceSampleCount: 81,
  }),
]);
