/* eslint-disable */
// GENERATED by tools/buildTenduPilotAssets.ts. Do not edit by hand.
import type { DryadTenduCohortAsset } from '../types/canonicalMotion';

function deepFreeze<T>(value: T): Readonly<T> {
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.freeze(value);
    Object.values(value as Record<string, unknown>).forEach(item => deepFreeze(item));
  }
  return value;
}

export const DRYAD_TENDU_COHORT_ASSET = deepFreeze({
  "schemaVersion": 1,
  "generatedFromDigest": "7351f3df72ac1c7fcce3936f21ea1b605ce4de137901f01129e6a98cfc36be24",
  "clip": {
    "schemaVersion": 1,
    "clipId": "dryad-tendu-cohort-100",
    "exerciseId": "tendu",
    "label": "Dryad Tendu · Kohorte 100 Versuche",
    "frameRateHz": 250,
    "coordinateSystem": "balletos_body_normalized_right_up_forward",
    "workingSide": "right",
    "cohortSize": 100,
    "participantCount": 10,
    "sourceTrialCount": 100,
    "provenance": {
      "datasetId": "dryad:10.5061/dryad.dncjsxm8v:2025-01-02:cohort-aggregate",
      "sourceUrl": "https://doi.org/10.5061/dryad.dncjsxm8v",
      "sourceKind": "optical_marker",
      "rightsStatus": "product_technical_signal_allowed",
      "licenseLabel": "CC0-1.0 · nicht-reversible Kohortenverdichtung",
      "pedagogicalStatus": "technical_only",
      "nicoleReviewStatus": "not_reviewed",
      "sourceDigest": "7351f3df72ac1c7fcce3936f21ea1b605ce4de137901f01129e6a98cfc36be24"
    },
    "frames": [
      {
        "timeUs": 0,
        "phaseId": "departure",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 9200,
        "phaseId": "departure",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.10113661420437986,
            "y": 0.03953168763812864,
            "z": 0.00023505858838295093,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.140380200125479,
            "y": 0.0001084913902698104,
            "z": 0.08009332159048113,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 18400,
        "phaseId": "departure",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.10262664631415998,
            "y": 0.03879559595679939,
            "z": 0.0005282412952345849,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.14099036120594047,
            "y": 0.00023758962735165106,
            "z": 0.08023906657026313,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 27600,
        "phaseId": "departure",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.10440609817359275,
            "y": 0.03790965195558671,
            "z": 0.0009112461525006203,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.14177652381590633,
            "y": 0.00039160602331716,
            "z": 0.08053354611970258,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 36800,
        "phaseId": "departure",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.10654981484216641,
            "y": 0.03674296346334686,
            "z": 0.0014485648277299547,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.1426832396682372,
            "y": 0.0005384594492288486,
            "z": 0.0808676556027741,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 46000,
        "phaseId": "departure",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.10999889668422931,
            "y": 0.035046124778904834,
            "z": 0.002344175692318883,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.14424577474943276,
            "y": 0.0007497307654313629,
            "z": 0.08145729484211986,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 55200,
        "phaseId": "departure",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.11310127695874607,
            "y": 0.03346400823927187,
            "z": 0.0032220588496861325,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.14587272322532993,
            "y": 0.0008060304845268312,
            "z": 0.08197665836731675,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 64400,
        "phaseId": "departure",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.11693338728330278,
            "y": 0.03130035577012888,
            "z": 0.004589196932981255,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.1481455004476935,
            "y": 0.0009110893372062578,
            "z": 0.0828494254797736,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 73600,
        "phaseId": "departure",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.12134718864685272,
            "y": 0.02891066422325838,
            "z": 0.006034743297387107,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.1511288276077579,
            "y": 0.000946175073420057,
            "z": 0.08374958937460628,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 82800,
        "phaseId": "departure",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.12699086829397085,
            "y": 0.025868032960461803,
            "z": 0.008022383201276207,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.15466767183844043,
            "y": 0.0009042106401060616,
            "z": 0.08496748325964591,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 92000,
        "phaseId": "departure",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.13247533034778275,
            "y": 0.022963127761335578,
            "z": 0.009774501660611928,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.1585462154271957,
            "y": 0.0008512509517550134,
            "z": 0.08632916549352412,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 92001,
        "phaseId": "extension",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.13525654131590317,
            "y": 0.021552845888774062,
            "z": 0.010617603553206411,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.16085220942329925,
            "y": 0.0007734647094527923,
            "z": 0.08707959844493908,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 107601,
        "phaseId": "extension",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.14919509243640897,
            "y": 0.014868983432061129,
            "z": 0.014233540174877438,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.17046452264210954,
            "y": 0.00020218204208319297,
            "z": 0.09010047165731339,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 123201,
        "phaseId": "extension",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.1634087143920375,
            "y": 0.008195589251374195,
            "z": 0.018507543944665215,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.18185694426220494,
            "y": -0.0005523625028283218,
            "z": 0.09414068272796351,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 138801,
        "phaseId": "extension",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.18016595205548636,
            "y": 0.0009593449340569646,
            "z": 0.023030385788582967,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.19723175175091343,
            "y": -0.0012195231558016291,
            "z": 0.09748967649979808,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 154401,
        "phaseId": "extension",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.19742896488429545,
            "y": -0.006995610966701336,
            "z": 0.02757520043342227,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.2137800207798271,
            "y": -0.002440802994035194,
            "z": 0.10143570681243731,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 170001,
        "phaseId": "extension",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.21741690595792892,
            "y": -0.014882577093013452,
            "z": 0.03145125383581915,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.23349529190206192,
            "y": -0.003740966028292345,
            "z": 0.10459649542976762,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 185601,
        "phaseId": "extension",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.2343914624722892,
            "y": -0.021318747267210204,
            "z": 0.0365898208657824,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.2524323638706195,
            "y": -0.005014005841564554,
            "z": 0.10741722314615232,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 201201,
        "phaseId": "extension",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.2531597869806181,
            "y": -0.02784182278330078,
            "z": 0.04010019987723369,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.2728864911089954,
            "y": -0.0060613291575638325,
            "z": 0.1119822411902073,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 216801,
        "phaseId": "extension",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.2704859800096753,
            "y": -0.03284351451004259,
            "z": 0.044520976408346014,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.2910277477451132,
            "y": -0.0066349407555961045,
            "z": 0.11473224383295065,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 232401,
        "phaseId": "extension",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.28509494801167556,
            "y": -0.036836429513978274,
            "z": 0.04744922726838035,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.30701747917843747,
            "y": -0.006921041038668099,
            "z": 0.11773325356983244,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 248001,
        "phaseId": "extension",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.30122681909432625,
            "y": -0.03995061833992659,
            "z": 0.04993865727482198,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.3218961291912319,
            "y": -0.007431266121967536,
            "z": 0.1206619497228094,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 248002,
        "phaseId": "full_extension",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.3045332200476498,
            "y": -0.04059049966199211,
            "z": 0.05102972305600341,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.3249532209004704,
            "y": -0.0075765358391916525,
            "z": 0.12157441457141845,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 262002,
        "phaseId": "full_extension",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.3156010432900077,
            "y": -0.04259373829417221,
            "z": 0.0543354002537047,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.33368654110068996,
            "y": -0.008073502722762218,
            "z": 0.1244840364637422,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 276002,
        "phaseId": "full_extension",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.3249883497706112,
            "y": -0.044375763236559805,
            "z": 0.05426266259305022,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.34134546565919743,
            "y": -0.008325054321425936,
            "z": 0.12613135363332306,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 290002,
        "phaseId": "full_extension",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.32970244286692796,
            "y": -0.04540405364031138,
            "z": 0.05567809306018033,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.3473620519755529,
            "y": -0.00850653409008454,
            "z": 0.1275903400976835,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 304002,
        "phaseId": "full_extension",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.3314809663352142,
            "y": -0.045873150647754636,
            "z": 0.05590361748248866,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.353750086129237,
            "y": -0.008487867157015055,
            "z": 0.1278453397261921,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 318002,
        "phaseId": "full_extension",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.3333525118226779,
            "y": -0.04645607087705853,
            "z": 0.05861131839279633,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.3540095556697938,
            "y": -0.008389404366634438,
            "z": 0.1284008905845747,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 332002,
        "phaseId": "full_extension",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.3317664636068327,
            "y": -0.046064908102574915,
            "z": 0.059710833017605616,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.35474431049165667,
            "y": -0.008255055240635968,
            "z": 0.12817763059381543,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 346002,
        "phaseId": "full_extension",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.32877826120258846,
            "y": -0.04562086115302786,
            "z": 0.059079338404279515,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.354613606761522,
            "y": -0.008144533090723664,
            "z": 0.1280240164173877,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 360002,
        "phaseId": "full_extension",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.3247722780332931,
            "y": -0.04487944896791394,
            "z": 0.05821731110581943,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.351166752416229,
            "y": -0.008011001689675282,
            "z": 0.1272583310201389,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 374002,
        "phaseId": "full_extension",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.3195146391357746,
            "y": -0.04373668483793317,
            "z": 0.057349072539693846,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.3443725930398467,
            "y": -0.00791654873709334,
            "z": 0.12622204515909524,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 388002,
        "phaseId": "full_extension",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.31209932143669894,
            "y": -0.042461866373870956,
            "z": 0.05661503059837707,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.3362222936796558,
            "y": -0.0077255594418690066,
            "z": 0.12504189519633618,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 388003,
        "phaseId": "return",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.31002024354881674,
            "y": -0.042001479458455095,
            "z": 0.0561443923089031,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.33340287687235204,
            "y": -0.0076593365856761995,
            "z": 0.12440860444403097,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 409003,
        "phaseId": "return",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.29591564800523495,
            "y": -0.03920377336015663,
            "z": 0.053858549361543426,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.31606224438853486,
            "y": -0.007335706903572904,
            "z": 0.12200443650169736,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 430003,
        "phaseId": "return",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.27809029987764367,
            "y": -0.03585591660034441,
            "z": 0.05027598149039389,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.29816152838266174,
            "y": -0.006600584975099031,
            "z": 0.12006391309942277,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 451003,
        "phaseId": "return",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.26162753003581596,
            "y": -0.031164222207691265,
            "z": 0.04624077053500121,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.279221169937941,
            "y": -0.00592686219548693,
            "z": 0.11669721106921682,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 472003,
        "phaseId": "return",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.24375784067974018,
            "y": -0.025684786497949565,
            "z": 0.04085420895797264,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.2585013850697744,
            "y": -0.005089441194675252,
            "z": 0.11349336223283886,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 493003,
        "phaseId": "return",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.22347570073569312,
            "y": -0.018369362994069383,
            "z": 0.03514938797750958,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.2379510576366913,
            "y": -0.004131615741954352,
            "z": 0.10941326577190946,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 514003,
        "phaseId": "return",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.2051858319517632,
            "y": -0.011618768144317539,
            "z": 0.029279370182765614,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.21987011201947976,
            "y": -0.0032283933329074936,
            "z": 0.10523342001705169,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 535003,
        "phaseId": "return",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.18723291191865832,
            "y": -0.004169797373069724,
            "z": 0.022782331828048393,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.20224698993879098,
            "y": -0.002081926625730915,
            "z": 0.10140121675036676,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 556003,
        "phaseId": "return",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.1708728405367384,
            "y": 0.0037851525255563276,
            "z": 0.017564626361396364,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.18745610899396736,
            "y": -0.0010330068457422101,
            "z": 0.09674296327692494,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 577003,
        "phaseId": "return",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.1551543520160194,
            "y": 0.012413878436593112,
            "z": 0.01215988166984942,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.1740634121578148,
            "y": -0.00016354688079582542,
            "z": 0.09200325055096063,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 598003,
        "phaseId": "return",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.14275667066824008,
            "y": 0.019614777237629527,
            "z": 0.007780009843234341,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.16503187513513218,
            "y": 0.0004802347077674307,
            "z": 0.0884877144643419,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 598004,
        "phaseId": "closure",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.14011138801893022,
            "y": 0.021110591790085044,
            "z": 0.006915176003415445,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.1633622613015067,
            "y": 0.0005414387639518897,
            "z": 0.08785611108832687,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 610004,
        "phaseId": "closure",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.13350689543540145,
            "y": 0.02530540391781961,
            "z": 0.004630953839588737,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.1586516049793614,
            "y": 0.0007402809318167614,
            "z": 0.08568272327235571,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 622004,
        "phaseId": "closure",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.12749331134198458,
            "y": 0.028242172444077087,
            "z": 0.0027781024648799117,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.15519123179864547,
            "y": 0.0008348902117761639,
            "z": 0.08392085080297056,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 634004,
        "phaseId": "closure",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.12209398897456265,
            "y": 0.031107571968321677,
            "z": 0.001343250631408905,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.15212464067188194,
            "y": 0.0009670870913723634,
            "z": 0.08268529898525473,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 646004,
        "phaseId": "closure",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.11741865623437008,
            "y": 0.03341541343086672,
            "z": 0.00029061250480885074,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.14984832492086791,
            "y": 0.0011288329485581623,
            "z": 0.08184678037460524,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 658004,
        "phaseId": "closure",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.1135448316536351,
            "y": 0.03542028719195608,
            "z": -0.0002087752147601408,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.14753890194632172,
            "y": 0.001083931464499057,
            "z": 0.08116918388007106,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 670004,
        "phaseId": "closure",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.11060820295431971,
            "y": 0.037269349600168096,
            "z": -0.001128747164382233,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.1460109060342264,
            "y": 0.0009790635359449163,
            "z": 0.08074451350122501,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 682004,
        "phaseId": "closure",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.10722111003813313,
            "y": 0.03843303611733254,
            "z": -0.0011301450006049444,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.14473708338244998,
            "y": 0.0008646085197255924,
            "z": 0.08032671292017834,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 694004,
        "phaseId": "closure",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.10520829392718804,
            "y": 0.0391514252368643,
            "z": -0.0011481677542809492,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.14351417744216594,
            "y": 0.0007362339377920879,
            "z": 0.0800149342793185,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 706004,
        "phaseId": "closure",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.10302623044676572,
            "y": 0.03995940602824512,
            "z": -0.0013422102960034092,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.14259506431523192,
            "y": 0.00048356181416715684,
            "z": 0.0798022103805504,
            "confidence": 0.95
          }
        }
      },
      {
        "timeUs": 718004,
        "phaseId": "closure",
        "joints": {
          "neck": {
            "x": 0,
            "y": 1,
            "z": 0,
            "confidence": 0.95
          },
          "ankleL": {
            "x": -0.1,
            "y": 0.04,
            "z": 0,
            "confidence": 0.95
          },
          "footL": {
            "x": -0.14,
            "y": 0,
            "z": 0.08,
            "confidence": 0.95
          },
          "ankleR": {
            "x": 0.10173377717801604,
            "y": 0.04040607055986884,
            "z": -0.0015659859901466858,
            "confidence": 0.95
          },
          "footR": {
            "x": 0.1419034460277,
            "y": 0.00028888600061190004,
            "z": 0.07969046575429356,
            "confidence": 0.95
          }
        }
      }
    ]
  },
  "phaseDispersion": [
    {
      "phaseId": "departure",
      "medianRadialSpread": 0.0015374420218936366,
      "p90RadialSpread": 0.010324831508830621,
      "sourceSampleCount": 1100
    },
    {
      "phaseId": "extension",
      "medianRadialSpread": 0.017368385442663063,
      "p90RadialSpread": 0.0445971513229903,
      "sourceSampleCount": 1100
    },
    {
      "phaseId": "full_extension",
      "medianRadialSpread": 0.024201610145363914,
      "p90RadialSpread": 0.04104746576971427,
      "sourceSampleCount": 1100
    },
    {
      "phaseId": "return",
      "medianRadialSpread": 0.014948083919037576,
      "p90RadialSpread": 0.04524164133995881,
      "sourceSampleCount": 1100
    },
    {
      "phaseId": "closure",
      "medianRadialSpread": 0.0038762685782700833,
      "p90RadialSpread": 0.016653768295483175,
      "sourceSampleCount": 1100
    }
  ]
}) as DryadTenduCohortAsset;

export const TENDU_PILOT_ASSET_MANIFEST = deepFreeze({
  "schemaVersion": 1,
  "dryad": {
    "datasetId": "dryad:10.5061/dryad.dncjsxm8v:2025-01-02",
    "sourceArchiveSha256": "caed963c17a250d8dad5bd14d56cac22ce936ff8e3e31af51b6402a2ebdca573",
    "generatedFromDigest": "7351f3df72ac1c7fcce3936f21ea1b605ce4de137901f01129e6a98cfc36be24",
    "participantCount": 10,
    "trialCount": 100,
    "generatedFrameCount": 55
  },
  "ucy": {
    "datasetId": "ucy-dancedb:ballet-ioanna-tacha-believer:bvh",
    "sourceBvhSha256": "29c342f7b1ef96f4eb3c66174d9a6c5bdd0e3904fedb46768ce72e529dfe8920",
    "sourceFrameCount": 11829,
    "inspectedFrameCount": 99,
    "stability": {
      "sampledFrames": 99,
      "mappedJointRatio": 1,
      "medianSegmentLengthCv": 1.318746262804364e-15,
      "stable": true
    },
    "exportedForm": "aggregate stability report only; no derived joint coordinates",
    "productStatus": "internal_research_only_do_not_ship"
  }
});
